version: '3.9'
name: 'next-app'

x-common-variables: &common-variables
  MYSQL_DATABASE: next-app
  MYSQL_USER: root
  MYSQL_PASSWORD: admin123

services:

  db:
    stdin_open: true
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
  api:
    stdin_open: true
    build:
      dockerfile: server/Dockerfile
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: db
    ports:
      - 8080:8080
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules:/node_modules
      - .:/app
    ports:
      - 3000:3000
  # nginx:
  #   build:
  #     context: ./docker/nginx
  #   #restart: "on-failure"
  #   restart: unless-stopped
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #     - "443:443"
  #   volumes:
  #     - "./build:/var/www/html"
  #     - "./docker/nginx/config:/etc/nginx/conf.do/:ro"
  #   command: '/bin/sh -c ''while:; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
